# Generated by Django 5.1.1 on 2024-10-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medical_license',
            field=models.ImageField(upload_to='licenses/'),
        ),
    ]
