# Generated by Django 5.1.1 on 2024-11-27 00:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('set', 'Set'), ('canceled', 'Canceled')], default='set', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
        ),
    ]
