# Generated by Django 5.1.1 on 2024-11-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='new_appointment_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='patient',
        ),
    ]
