# Generated by Django 5.1.1 on 2024-11-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_notification_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed')], max_length=20),
        ),
    ]
