# Generated by Django 5.1.1 on 2024-11-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('set', 'Set'), ('canceled', 'Canceled'), ('reschedule_accepted', 'Reschedule Accepted'), ('reschedule_rejected', 'Reschedule Rejected')], default='set', max_length=20),
        ),
    ]
