# Generated by Django 5.1.1 on 2024-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('trash', 'Trash')], max_length=20),
        ),
    ]
